import 'package:fitfusion_app/config/assets.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          WelcomeScreen(),
        ]),
      ),
    );
  }
}

class WelcomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFF131414),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 20,
                top: 526,
                child: Container(
                  width: 350,
                  height: 296,
                  decoration: ShapeDecoration(
                    color: Colors.white.withOpacity(0.029999999329447746),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 547,
                child: SizedBox(
                  width: 303,
                  height: 80,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Latih ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0.05,
                          ),
                        ),
                        TextSpan(
                          text: 'Pikiran',
                          style: TextStyle(
                            color: Color(0xFFB4F45F),
                            fontSize: 25,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0.05,
                          ),
                        ),
                        TextSpan(
                          text: ' dan ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0.05,
                          ),
                        ),
                        TextSpan(
                          text: 'Tubuh',
                          style: TextStyle(
                            color: Color(0xFFB4F45F),
                            fontSize: 25,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0.05,
                          ),
                        ),
                        TextSpan(
                          text: ' Anda ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 25,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0.05,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 627,
                child: SizedBox(
                  width: 298,
                  height: 92,
                  child: Text(
                    'Aktivitas fisik yang teratur dapat meningkatkan kekuatan otot dan meningkatkan daya tahan Anda. Olahraga memberikan oksigen dan nutrisi ke tubuh Anda\n',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white.withOpacity(0.75),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0.12,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 739,
                child: Container(
                  width: 129,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: Color(0xFFB4F45F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Mulai',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF131414),
                          fontSize: 14,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w700,
                          height: 0.11,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 79,
                top: 56,
                child: Text(
                  'FitFusion',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFFB4F45F),
                    fontSize: 50,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 0.02,
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: -29,
                child: Container(
                  width: 370,
                  height: 556,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/people.png'),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
